"use strict";
(function(){
  const STYLE_KEY="prayerDesignerInterfaceClockStylesV3",POS_KEY="prayerDesignerInterfaceHeaderPositionsV1";
  const TARGETS=["#liveClockTime","#liveClockDate"];
  function pad(v){return String(v).padStart(2,"0");}
  function injectStyles(){if(document.getElementById("interfaceClockStyles"))return;const s=document.createElement("style");s.id="interfaceClockStyles";s.textContent=`
    .topbar.web-interface-header{direction:ltr!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:10px!important;padding:8px 12px!important;min-height:48px!important;position:relative!important;overflow:visible!important}
    .interface-clock-card,.interface-date-card{min-width:0;display:flex!important;align-items:center!important;gap:5px!important;padding:6px 9px!important;border:1px solid rgba(255,255,255,.14)!important;border-radius:10px!important;background:linear-gradient(145deg,rgba(20,39,51,.94),rgba(8,24,35,.94))!important;box-shadow:0 4px 14px rgba(0,0,0,.14)!important;user-select:none!important;position:relative;z-index:3}
    body.manual-edit-on .header-draggable{cursor:grab!important;touch-action:none!important}
    body.manual-edit-on .header-draggable:active{cursor:grabbing!important}
    body.manual-edit-off .header-draggable{cursor:default!important;touch-action:auto!important}
    .topbar.web-interface-header #saveToPhoneBtn{margin:0!important;flex:0 0 auto!important;padding:6px 8px!important;min-height:30px!important;position:relative;z-index:2}
    .interface-clock-icon,.interface-date-icon{font-size:13px!important;line-height:1!important;opacity:.9;pointer-events:none}
    #liveClockTime{display:flex!important;align-items:baseline!important;gap:4px!important;direction:ltr!important;color:#f8fbfd;font-size:17px;font-weight:800;line-height:1.1;font-variant-numeric:tabular-nums;white-space:nowrap}
    #liveClockDate{display:flex!important;align-items:center!important;gap:4px!important;direction:ltr!important;color:#dfe8ed;font-size:14px;font-weight:700;line-height:1.1;font-variant-numeric:tabular-nums;white-space:nowrap}
    #liveClockTime *,#liveClockDate *{font-family:inherit!important;font-size:inherit!important;font-weight:inherit!important;color:inherit!important;text-shadow:inherit!important}
    #liveClockDate .interface-date-sep{opacity:.52}
    @media(max-width:600px){.topbar.web-interface-header{gap:5px!important;padding:6px 4px!important}.interface-clock-card,.interface-date-card{padding:5px 6px!important;gap:3px!important}.interface-clock-icon,.interface-date-icon{display:none!important}#liveClockTime{font-size:12.5px}#liveClockDate{font-size:11px}.topbar.web-interface-header #saveToPhoneBtn{padding:5px 6px!important;font-size:10.5px!important}}
  `;document.head.appendChild(s);}
  function clockEl(){const d=document.createElement("div");d.className="interface-clock-card header-draggable";d.dataset.headerItem="clock";d.innerHTML='<div class="interface-clock-icon">◷</div><div id="liveClockTime"><div id="liveClockDigits">12:00:00</div><div id="liveClockPeriod">ص</div></div>';return d;}
  function dateEl(){const d=document.createElement("div");d.className="interface-date-card header-draggable";d.dataset.headerItem="date";d.innerHTML='<div class="interface-date-icon">▣</div><div id="liveClockDate"><div id="liveDateDay">01</div><div class="interface-date-sep">/</div><div id="liveDateMonth">01</div><div class="interface-date-sep">/</div><div id="liveDateYear">2026</div></div>';return d;}
  function build(){const h=document.querySelector(".topbar");if(!h)return false;h.classList.add("web-interface-header");h.querySelectorAll(".brand,.interface-clock-card,.interface-date-card").forEach(x=>x.remove());const save=h.querySelector("#saveToPhoneBtn,#exportBtn"),date=dateEl(),clock=clockEl();h.append(date);if(save)h.append(save);h.append(clock);return true;}
  function renameSave(){const b=document.querySelector("#saveToPhoneBtn");if(!b)return;b.title="حفظ الصورة";const span=b.querySelector("span");if(span)span.textContent="حفظ الصورة";else b.textContent="حفظ الصورة";}
  function update(){const n=new Date();let h=n.getHours(),p=h<12?"ص":"م";h=((h+11)%12)+1;const q=id=>document.getElementById(id);if(q("liveClockDigits"))q("liveClockDigits").textContent=`${pad(h)}:${pad(n.getMinutes())}:${pad(n.getSeconds())}`;if(q("liveClockPeriod"))q("liveClockPeriod").textContent=p;if(q("liveDateDay"))q("liveDateDay").textContent=pad(n.getDate());if(q("liveDateMonth"))q("liveDateMonth").textContent=pad(n.getMonth()+1);if(q("liveDateYear"))q("liveDateYear").textContent=n.getFullYear();}
  function addOptions(){const sel=document.getElementById("elementSelect");if(!sel)return;[["#liveClockTime","الساعة"],["#liveClockDate","التاريخ"]].forEach(([v,t])=>{const o=Array.from(sel.options).find(x=>x.value===v);if(o)o.textContent=t;else sel.add(new Option(t,v));});}
  function state(){try{return JSON.parse(localStorage.getItem(STYLE_KEY)||"{}")||{};}catch(_){return {};}}
  function setImportant(el,prop,value){if(value!==undefined&&value!==null&&value!=="")el.style.setProperty(prop,value,"important");}
  function applySaved(sel,st){const el=document.querySelector(sel);if(!el||!st)return;setImportant(el,"font-family",st.family);setImportant(el,"font-size",st.size);setImportant(el,"font-weight",st.weight);setImportant(el,"color",st.color);setImportant(el,"text-align",st.align);setImportant(el,"text-shadow",st.shadow);}
  function restoreStyles(){const all=state();TARGETS.forEach(sel=>applySaved(sel,all[sel]));}
  function selected(){const v=document.getElementById("elementSelect")?.value;return TARGETS.includes(v)?v:null;}
  function shadowValue(v){return({none:"none",black:"0 2px 4px rgba(0,0,0,.85)",gold:"0 2px 5px #b98a28",green:"0 2px 5px #1f8a55"})[v]||v||"none";}
  function applyOne(id){const sel=selected(),el=sel&&document.querySelector(sel);if(!el)return;let prop,value;if(id==="fontFamily"){prop="font-family";value=document.getElementById(id)?.value;}else if(id==="fontSize"){prop="font-size";value=(document.getElementById(id)?.value||"")+"px";}else if(id==="fontWeight"){prop="font-weight";value=document.getElementById(id)?.value;}else if(id==="fontColor"){prop="color";value=document.getElementById(id)?.value;}else if(id==="textAlign"){prop="text-align";value=document.getElementById(id)?.value;}else if(id==="textShadow"){prop="text-shadow";value=shadowValue(document.getElementById(id)?.value);}else return;setImportant(el,prop,value);const cs=getComputedStyle(el),all=state();all[sel]={family:cs.fontFamily,size:cs.fontSize,weight:cs.fontWeight,color:cs.color,align:cs.textAlign,shadow:cs.textShadow};try{localStorage.setItem(STYLE_KEY,JSON.stringify(all));}catch(_){}}
  function syncControls(){const sel=selected(),el=sel&&document.querySelector(sel);if(!el)return;const cs=getComputedStyle(el),q=id=>document.getElementById(id);if(q("fontSize"))q("fontSize").value=parseFloat(cs.fontSize)||14;if(q("fontWeight"))q("fontWeight").value=cs.fontWeight;if(q("fontColor")){const m=cs.color.match(/\d+/g);if(m&&m.length>=3)q("fontColor").value="#"+m.slice(0,3).map(n=>(+n).toString(16).padStart(2,"0")).join("");}}
  function bindFormatting(){if(document.documentElement.dataset.headerFormatBound)return;document.documentElement.dataset.headerFormatBound="1";const ids=["fontFamily","fontSize","fontWeight","fontColor","textAlign","textShadow"];
    document.addEventListener("input",e=>{if(ids.includes(e.target?.id)&&selected())applyOne(e.target.id);},true);
    document.addEventListener("change",e=>{if(e.target?.id==="elementSelect")setTimeout(syncControls,0);if(ids.includes(e.target?.id)&&selected())applyOne(e.target.id);},true);
    document.addEventListener("click",e=>{const sw=e.target?.closest?.("#designColorPalette .palette-color,.palette-color");const sel=selected();if(!sw||!sel)return;const color=sw.dataset.color||sw.dataset.value;if(!color)return;const el=document.querySelector(sel);setImportant(el,"color",color);const input=document.getElementById("fontColor");if(input)input.value=color;const all=state(),cs=getComputedStyle(el);all[sel]={...(all[sel]||{}),color:cs.color};try{localStorage.setItem(STYLE_KEY,JSON.stringify(all));}catch(_){}},true);
  }
  function readPos(){try{return JSON.parse(localStorage.getItem(POS_KEY)||"{}")||{};}catch(_){return {};}}
  function savePos(el){const p=readPos();p[el.dataset.headerItem]={x:Number(el.dataset.x||0),y:Number(el.dataset.y||0)};try{localStorage.setItem(POS_KEY,JSON.stringify(p));}catch(_){}}
  function setPos(el,x,y){el.dataset.x=x;el.dataset.y=y;el.style.transform=`translate(${x}px,${y}px)`;}
  function manualOn(){return window.PrayerManualEdit?.isEnabled?.()===true||window.__manualPreviewEditingEnabled===true;}
  function bindDrag(el){if(el.dataset.dragBound)return;el.dataset.dragBound="1";const old=readPos()[el.dataset.headerItem];if(old)setPos(el,old.x||0,old.y||0);let active=false,sx=0,sy=0,bx=0,by=0;el.addEventListener("pointerdown",e=>{if(!manualOn())return;if(e.button!==undefined&&e.button!==0)return;active=true;sx=e.clientX;sy=e.clientY;bx=Number(el.dataset.x||0);by=Number(el.dataset.y||0);el.setPointerCapture?.(e.pointerId);e.preventDefault();});el.addEventListener("pointermove",e=>{if(!active)return;if(!manualOn()){active=false;return;}setPos(el,bx+e.clientX-sx,by+e.clientY-sy);});const end=()=>{if(!active)return;active=false;savePos(el);};el.addEventListener("pointerup",end);el.addEventListener("pointercancel",end);}
  function ensure(){renameSave();document.querySelectorAll(".header-draggable").forEach(bindDrag);}
  function init(){injectStyles();if(!build())return;addOptions();restoreStyles();bindFormatting();update();ensure();setTimeout(ensure,150);setTimeout(ensure,800);setInterval(update,1000);window.addEventListener("aoqatModulesReady",ensure);document.addEventListener("visibilitychange",()=>{if(!document.hidden)update();});}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();