(function(){'use strict';const C=window.AoqatPrayerAlarmCore,KEY='aoqatPrayerAlarmV1',N=window.AndroidNative, native=!!N?.configurePrayerAlarm;let state;try{state=C.normalize(JSON.parse(native?N.readPrayerAlarmSettings():localStorage.getItem(KEY)||'{}'));}catch(_){state=C.normalize();}
 let box,alarmOpen=false,editing='',active=null,snoozed=null,last=Date.now(),context,osc,gain,pulse,endTimer,previewTimer,toneAudio,customURL,soundGeneration=0;const seen=new Set();const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function rows(){try{return JSON.parse(native?N.readPrayerRows():localStorage.getItem('aoqatAdhanRows')||'[]');}catch(_){return [];}}
 function save(){localStorage.setItem(KEY,JSON.stringify(state));if(native)N.configurePrayerAlarm(JSON.stringify(state));}
 const clock=at=>new Date(at).toLocaleTimeString('ar-IQ',{hour:'2-digit',minute:'2-digit'});
 function draw(){if(!box?.isConnected)return;const next=C.next(rows(),{...state,enabled:true,items:Object.fromEntries(C.ids.map(id=>[id,{...state.items[id],enabled:true}]))});box.querySelector('#paContent').innerHTML=`<div class="pa-master-row"><span>تشغيل منبّه الصلاة</span><button type="button" id="paMaster" class="pa-switch ${state.enabled?'pa-on':''}" aria-pressed="${state.enabled}" aria-label="${state.enabled?'إيقاف منبّه الصلاة':'تشغيل منبّه الصلاة'}">${state.enabled?'تشغيل':'إيقاف'}</button></div><fieldset id="paItems" ${state.enabled?'':'disabled'}>${C.ids.map(id=>`<div class="pa-alarm"><button type="button" class="pa-edit" data-pa-edit="${id}"><strong>${esc(state.items[id].label)}</strong><span>${next[id]?clock(next[id].at):'الموعد يحتاج مواقيت قاعدة البيانات'}</span></button><button type="button" class="pa-switch ${state.items[id].enabled?'pa-on':''}" data-pa-toggle="${id}" aria-pressed="${state.items[id].enabled}">${state.items[id].enabled?'تشغيل':'إيقاف'}</button></div>`).join('')}<p class="pa-note">المواعيد من قاعدة البيانات. يُحسب ثلث الليل الأخير من المغرب إلى فجر اليوم التالي.</p><p class="pa-note">${native?esc(N.prayerAlarmReadiness?.()||'الرنين يعمل بالخلفية بعد منح أذونات المنبّه والإشعارات.'):'على الويب: الرنين أثناء فتح الصفحة وبعد تفاعلك معها؛ الرنين بالخلفية وشاشة القفل في تطبيق Android.'}</p></fieldset><div id="paEditor"></div><p id="paStatus" role="status"></p>`;
 box.querySelector('#paMaster').onclick=()=>{unlock();state.enabled=!state.enabled;if(!native&&state.enabled&&'Notification' in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{});if(!state.enabled){stop();snoozed=null;editing='';}save();draw();};box.querySelectorAll('[data-pa-toggle]').forEach(b=>b.onclick=()=>{unlock();const id=b.dataset.paToggle;state.items[id].enabled=!state.items[id].enabled;if(!state.items[id].enabled&&active?.id===id)stop();if(snoozed?.id===id)snoozed=null;save();draw();});box.querySelectorAll('[data-pa-edit]').forEach(b=>b.onclick=()=>editor(b.dataset.paEdit));if(editing&&state.enabled)editor(editing);}
 function editor(id){if(!state.enabled)return;editing=id;const s=state.items[id],e=box.querySelector('#paEditor');e.innerHTML=`<section class="pa-settings"><h4>تعديل منبّه ${C.names[id]}</h4><p class="pa-note">الوقت يتحدث تلقائيًا حسب مواقيت الصلاة.</p><label>التكرار<select id="paRepeat"><option value="daily">كل يوم</option><option value="once">مرة واحدة فقط</option><option value="days">أيام محددة</option></select></label><div id="paDays">${['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'].map((n,i)=>`<label><input type="checkbox" data-pa-day="${i}" ${s.days.includes(i)?'checked':''}>${n}</label>`).join('')}</div><label>النغمة<select id="paTone"><option value="default">نغمة المنبّه</option><option value="soft">نغمة هادئة</option>${['custom','system'].includes(s.tone.kind)?`<option value="${s.tone.kind}">${esc(s.tone.name)}</option>`:''}</select></label><button type="button" id="paChoose">اختيار نغمة من الهاتف</button>${native?'<button type="button" id="paSystemTone">نغمات الهاتف</button>':''}<input type="file" id="paFile" accept="audio/*" hidden><label>التسمية<input id="paLabel" maxlength="80" value="${esc(s.label)}"></label><label>مدة الرنين (دقيقة)<input id="paDuration" type="number" min="1" max="30" value="${s.duration}"></label><label>مدة الغفوة (دقيقة)<input id="paSnooze" type="number" min="1" max="30" value="${s.snooze}"></label><label>عدد الغفوات<input id="paCount" type="number" min="0" max="10" value="${s.count}"></label><label id="paDeleteRow">حذف إعداد المنبّه بعد رنين المرة الواحدة<input id="paDelete" type="checkbox" ${s.deleteAfter?'checked':''}></label><div class="pa-actions"><button type="button" id="paSave">✓ حفظ</button><button type="button" id="paCancel">إلغاء</button><button type="button" id="paPreview">تجربة النغمة</button><button type="button" id="paStopPreview">إيقاف التجربة</button></div></section>`;
 const $=id=>e.querySelector('#'+id);$('paRepeat').value=s.repeat;$('paTone').value=s.tone.kind;const sync=()=>{$('paDays').hidden=$('paRepeat').value!=='days';$('paDeleteRow').hidden=$('paRepeat').value!=='once';};$('paRepeat').onchange=sync;sync();
 $('paSave').onclick=()=>{const days=[...e.querySelectorAll('[data-pa-day]:checked')].map(b=>Number(b.dataset.paDay));if($('paRepeat').value==='days'&&!days.length){box.querySelector('#paStatus').textContent='اختر يومًا واحدًا على الأقل';return;}state.items[id]=C.item(id,{...s,label:$('paLabel').value,repeat:$('paRepeat').value,days,duration:$('paDuration').value,snooze:$('paSnooze').value,count:$('paCount').value,deleteAfter:$('paDelete').checked,tone:$('paTone').value===s.tone.kind?s.tone:{kind:$('paTone').value}});save();editing='';draw();box.querySelector('#paStatus').textContent='تم حفظ المنبّه';};$('paCancel').onclick=()=>{editing='';e.innerHTML='';};$('paPreview').onclick=()=>{unlock();if(native)N.previewPrayerAlarm(id);else{sound({...s,tone:$('paTone').value===s.tone.kind?s.tone:{kind:$('paTone').value}},id);clearTimeout(previewTimer);previewTimer=setTimeout(silence,5000);}};$('paStopPreview').onclick=()=>{if(native)N.stopPrayerAlarm();else silence();};$('paChoose').onclick=()=>native?N.choosePrayerAlarmTone(id,false):$('paFile').click();if(native)$('paSystemTone').onclick=()=>N.choosePrayerAlarmTone(id,true);
 $('paFile').onchange=async event=>{const f=event.target.files[0];if(!f)return;if(!f.type.startsWith('audio/')||f.size>25*1024*1024){box.querySelector('#paStatus').textContent='اختر صوتًا أقل من 25 ميغابايت';return;}try{const db=await audioDB();await new Promise((resolve,reject)=>{const tx=db.transaction('tones','readwrite');tx.objectStore('tones').put(f,id);tx.oncomplete=resolve;tx.onerror=reject;});db.close();s.tone={kind:'custom',value:'',name:f.name};save();editor(id);}catch(_){box.querySelector('#paStatus').textContent='تعذر حفظ النغمة';}};
 }
 function audioDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('aoqat-prayer-alarm-audio',1);r.onupgradeneeded=()=>r.result.createObjectStore('tones');r.onsuccess=()=>resolve(r.result);r.onerror=reject;});}
 function unlock(){if(native)return;try{context||=new (window.AudioContext||window.webkitAudioContext)();context.resume();}catch(_){} }
 async function sound(s,id){silence();const generation=soundGeneration;if(s.tone.kind==='custom'){try{const db=await audioDB();const file=await new Promise((resolve,reject)=>{const tx=db.transaction('tones');const r=tx.objectStore('tones').get(id);r.onsuccess=()=>resolve(r.result);r.onerror=reject;});db.close();if(generation!==soundGeneration)return;if(file){customURL=URL.createObjectURL(file);toneAudio=new Audio(customURL);toneAudio.loop=true;await toneAudio.play();return;}}catch(_){}}
 if(generation!==soundGeneration)return;unlock();if(!context)return;osc=context.createOscillator();gain=context.createGain();osc.frequency.value=s.tone.kind==='soft'?660:880;gain.gain.value=.12;osc.connect(gain);gain.connect(context.destination);osc.start();let on=true;pulse=setInterval(()=>{on=!on;if(gain)gain.gain.setValueAtTime(on?.12:0,context.currentTime);},450);}
 function silence(){soundGeneration++;clearInterval(pulse);clearTimeout(previewTimer);try{osc?.stop();}catch(_){}osc=null;gain=null;toneAudio?.pause();toneAudio=null;if(customURL)URL.revokeObjectURL(customURL);customURL=null;}
 function stop(){silence();clearTimeout(endTimer);active=null;document.getElementById('paRinging')?.remove();}
 function finish(id){const s=state.items[id];if(s.repeat==='once'){state.items[id]=s.deleteAfter?C.item(id):{...s,enabled:false};save();draw();}}
 function ring(e,count=0){if(!C.allowed(state,e)||fridaySuppressed(e))return;stop();active={...e,count};if(!native&&count===0)window.aoqatPrayerDueNotification?.(e.id==='dhuhr'&&new Date(e.at).getDay()===5?'friday':e.id,e.at);sound(state.items[e.id],e.id);const dialog=document.createElement('section');dialog.id='paRinging';dialog.dir='rtl';dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');dialog.innerHTML=`<h2>⏰ ${esc(state.items[e.id].label)}</h2><p>${clock(e.at)}</p><button type="button" id="paDismiss">إيقاف</button><button type="button" id="paSnoozeNow" ${count>=state.items[e.id].count?'disabled':''}>غفوة</button>`;document.body.append(dialog);dialog.querySelector('#paDismiss').onclick=()=>{stop();finish(e.id);};dialog.querySelector('#paSnoozeNow').onclick=()=>{snoozed={id:e.id,at:Date.now()+state.items[e.id].snooze*60000,count:count+1};stop();};endTimer=setTimeout(()=>{stop();finish(e.id);},state.items[e.id].duration*60000);}
 function fridaySuppressed(e){try{return e.id==='dhuhr'&&new Date(e.at).getDay()===5&&JSON.parse(localStorage.getItem('aoqatAdhanV1')||'{}').friday?.enabled===true;}catch(_){return false;}}
 function tick(){const now=Date.now();if(!native&&state.enabled){if(snoozed&&now>=snoozed.at){const e=snoozed;snoozed=null;ring(e,e.count);}for(const e of C.events(rows(),new Date(now),2))if(e.at>last&&e.at<=now&&now-e.at<120000&&C.allowed(state,e)&&!seen.has(e.id+e.at)){seen.add(e.id+e.at);ring(e);}}last=now;}
 function mount(){const panel=document.getElementById('adhanPanel');if(!panel||panel.querySelector('#prayerAlarmPanel'))return;const toggle=document.createElement('button');toggle.type='button';toggle.id='paOpen';toggle.className='ad-section-toggle';toggle.setAttribute('aria-controls','prayerAlarmPanel');toggle.innerHTML='<span class="ad-section-icon" aria-hidden="true">⏰</span><span>منبّه الصلاة</span><span class="ad-section-chevron" aria-hidden="true">‹</span>';box=document.createElement('section');box.id='prayerAlarmPanel';box.className='ad-card';box.innerHTML='<div id="paContent"></div>';const sync=()=>{box.hidden=!alarmOpen;toggle.setAttribute('aria-expanded',String(alarmOpen));toggle.classList.toggle('ad-section-active',alarmOpen);};toggle.onclick=()=>{alarmOpen=!alarmOpen;if(!alarmOpen){editing='';box.querySelector('#paEditor').innerHTML='';}sync();if(alarmOpen)box.querySelector('[data-subwindow-back]')?.focus({preventScroll:true});else toggle.focus({preventScroll:true});};panel.append(toggle,box);sync();draw();}
 window.aoqatPrayerAlarmToneChosen=(id,tone)=>{if(!C.ids.includes(id))return;state.items[id].tone=tone;save();draw();};window.aoqatPrayerAlarmNativeSettings=s=>{state=C.normalize(s);localStorage.setItem(KEY,JSON.stringify(state));draw();};
 const css=document.createElement('link');css.rel='stylesheet';css.href='css/prayer-alarm.css';document.head.append(css);new MutationObserver(mount).observe(document.body,{childList:true,subtree:true});mount();setInterval(tick,1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){tick();draw();}});
})();

