const prayerFixture=require('./prayer-db-fixture.cjs');
const {chromium}=require('playwright'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
(async()=>{const server=spawn('python3',['-m','http.server','8780'],{stdio:'ignore'});let browser;try{
 await new Promise(r=>setTimeout(r,700));browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Baghdad',serviceWorkers:'block'}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(()=>{const D=Date;window.fridayNow=new D('2026-10-09T11:23:00+03:00').getTime();window.Date=class extends D{constructor(...args){super(...(args.length?args:[fridayNow]))}static now(){return fridayNow}};if(!localStorage.fridaySeed){localStorage.fridaySeed='1';localStorage.aoqatAdhanV1=JSON.stringify({enabled:false,reminder:5,modes:{dhuhr:'vibrate'},friday:{enabled:false,reminder:20,sermon:40,firstSound:false,secondSound:false,quiet:true}});localStorage.aoqatPrayerAlarmV1=JSON.stringify({enabled:true,items:{dhuhr:{enabled:true}}});}});
 await p.route('**/rest/v1/annual_prayer_times**',r=>r.fulfill({json:prayerFixture(r,[{gregorian_month:10,gregorian_day:9,fajr:'4:43',sunrise:'6:04',dhuhr:'11:59',asr:'3:22',maghrib:'5:53',isha:'7:13'},{gregorian_month:10,gregorian_day:10,fajr:'4:43',dhuhr:'11:59',asr:'3:22'}])}));
 async function open(){await p.waitForSelector('[data-drawer="adhanIqama"]',{state:'attached'});await p.evaluate(()=>document.body.classList.add('design-menu-open'));await p.locator('[data-drawer="adhanIqama"]').click();await p.getByRole('button',{name:'🔊 الأذان والتنبيه',exact:true}).click();await p.locator('[data-ad-section="friday"]').click();await p.waitForSelector('#adSection-friday:not([hidden])');}
 async function time(v,label,clock){await p.evaluate(v=>{fridayNow=new Date(v).getTime()},v);await p.waitForFunction(({label,clock})=>document.getElementById('iqamaLabel')?.textContent===label&&document.getElementById('iqamaCountdown')?.textContent===clock,{label,clock});}
 await p.goto('http://127.0.0.1:8780',{waitUntil:'domcontentloaded'});await open();assert.ok(await p.getByRole('heading',{name:'تخصيص صلاة الجمعة',exact:true}).isVisible());await p.locator('[data-friday="enabled"]').check();assert.equal(await p.locator('[data-friday="sermon"]').inputValue(),'40');await p.locator('[data-friday="quietTiming"]').selectOption('custom');await p.locator('[data-friday="quietBefore"]').fill('10');await p.locator('[data-friday="quietBefore"]').dispatchEvent('change');await p.locator('#adSection-friday [data-subwindow-back]').click();
 await time('2026-10-09T11:24:00+03:00','باقي على أذان الجمعة الأول','20:00');await time('2026-10-09T11:44:00+03:00','باقي على الخطبة','15:00');await time('2026-10-09T11:59:00+03:00','مضى على الخطبة','00:00');assert.equal(await p.locator('#paRinging').count(),0);await time('2026-10-09T12:17:00+03:00','مضى على الخطبة','18:00');await time('2026-10-09T12:39:00+03:00','باقي على الإقامة','00:00');
 const settings=await p.evaluate(()=>JSON.parse(localStorage.aoqatAdhanV1));assert.equal(settings.enabled,false);assert.equal(settings.reminder,5);assert.equal(settings.modes.dhuhr,'vibrate');assert.equal(settings.friday.quietBefore,10);await p.reload({waitUntil:'domcontentloaded'});await open();assert.ok(await p.locator('[data-friday="enabled"]').isChecked());assert.equal(await p.locator('[data-friday="quietBefore"]').inputValue(),'10');assert.deepEqual(errors,[]);console.log('Friday settings, back navigation, exact transitions, noon suppression and persistence passed');
}finally{await browser?.close();server.kill()}})().catch(e=>{console.error(e);process.exit(1)});
