const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const {chromium} = require('playwright');
const root=process.cwd();
const sandbox={window:{}};
vm.runInNewContext(fs.readFileSync(root+'/js/iqama-timing.js','utf8'),sandbox);
const timing=sandbox.window.AoqatIqamaTiming;
const before={fajr:20,dhuhr:10,asr:15,maghrib:5,isha:30};
const after={fajr:5,dhuhr:15,asr:20,maghrib:15,isha:30};
for(const id of Object.keys(before)){
  const prayers=[{id,startSeconds:1000}],iqama=1000+before[id]*60,end=iqama+after[id]*60;
  assert.equal(timing.state(999,prayers,before,after),null);
  assert.equal(timing.state(1000,prayers,before,after).seconds,before[id]*60);
  assert.equal(timing.state(iqama-1,prayers,before,after).seconds,1);
  assert.equal(timing.state(iqama,prayers,before,after).phase,'elapsed');
  assert.equal(timing.state(iqama,prayers,before,after).seconds,0);
  assert.equal(timing.state(end-1,prayers,before,after).seconds,after[id]*60-1);
  assert.equal(timing.state(end,prayers,before,after),null);
  assert.equal(timing.state(end+3600,prayers,before,after),null);
}
assert.equal(timing.normalize({maghrib:5},before).maghrib,5);
assert.equal(timing.normalize({maghrib:-1},before).maghrib,5);
const maghrib=[{id:'maghrib',startSeconds:17*3600+54*60}];
assert.equal(timing.state(18*3600+2*60+23,maghrib,before,after).seconds,203);
assert.equal(timing.state(18*3600+6*60+19,maghrib,before,after).seconds,439);
assert.equal(timing.state(18*3600+12*60+5,maghrib,before,after).seconds,785);
console.log('PASS: five prayers, countdown/elapsed boundaries, saved settings, screenshot times');
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||undefined,args:['--no-sandbox']});
  const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Baghdad'});
  await context.addInitScript(()=>{
    const RealDate=Date;let now=new RealDate('2026-09-30T17:54:00+03:00').getTime();
    window.__setTestTime=value=>{now=new RealDate(value).getTime()};
    window.Date=class extends RealDate {constructor(...args){super(...(args.length?args:[now]))}static now(){return now}};
    if(!localStorage.getItem('aoqatIqamaMinutesV1'))localStorage.setItem('aoqatIqamaMinutesV1',JSON.stringify({fajr:20,dhuhr:10,asr:10,maghrib:5,isha:10,friday:15}));
    localStorage.setItem('aoqatInterfaceVisibilityV1',JSON.stringify({clock:true,date:true,adhan:true,iqama:true}));
  });
  const page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*.supabase.co/**',route=>route.fulfill({contentType:'application/json',body:JSON.stringify([{gregorian_month:9,gregorian_day:30,fajr:'4:44',sunrise:'6:02',dhuhr:'12:00',asr:'3:23',maghrib:'5:54',isha:'7:14'}])}));
  await page.goto('http://127.0.0.1:8765/');
  await page.waitForSelector('#afterIqamaPanel',{state:'attached'});
  await page.waitForTimeout(1500);
  await page.evaluate(()=>document.body.classList.add('design-menu-open'));
  await page.locator('[data-drawer="datePrayer"]').click();
  assert.equal(await page.locator('#webDatePrayerTemp [data-panel="afterIqamaPanel"]').count(),1);
  assert.equal(await page.locator('#webDatePrayerTemp .main-action').count(),4);
  await page.locator('[data-panel="afterIqamaPanel"]').click();
  assert.equal(await page.locator('#webSubTitle').innerText(),'اوقات بعد الاقامة');
  assert.equal(await page.locator('#afterIqamaPanel select').count(),5);
  assert.equal(await page.locator('#afterIqamaPanel [data-after-iqama="maghrib"]').inputValue(),'10');
  await page.locator('#afterIqamaPanel [data-after-iqama="maghrib"]').selectOption('15');
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('aoqatIqamaMinutesV1')).maghrib),5);
  await page.locator('.web-back').click();
  await page.locator('.web-back').click();
  await page.locator('[data-drawer="settings"]').click();
  assert.equal(await page.locator('#webSettingsTemp [data-panel="afterIqamaPanel"]').count(),0);
  assert.equal(await page.locator('#webSettingsTemp .main-action').count(),3);
  await page.reload();await page.waitForSelector('#afterIqamaPanel',{state:'attached'});
  assert.equal(await page.locator('[data-after-iqama="maghrib"]').inputValue(),'15');
  await page.evaluate(()=>document.body.classList.remove('design-menu-open'));
  async function time(value){await page.evaluate(value=>window.__setTestTime(value),value);await page.waitForTimeout(1100);}
  await time('2026-09-30T17:54:00+03:00');assert.equal(await page.locator('#iqamaCountdown').innerText(),'05:00');
  await time('2026-09-30T17:58:59+03:00');assert.equal(await page.locator('#iqamaCountdown').innerText(),'00:01');
  await time('2026-09-30T17:59:00+03:00');assert.equal(await page.locator('#iqamaLabel').innerText(),'مضى على الإقامة');assert.equal(await page.locator('#iqamaCountdown').innerText(),'00:00');
  await time('2026-09-30T18:02:23+03:00');assert.equal(await page.locator('#iqamaCountdown').innerText(),'03:23');
  await time('2026-09-30T18:06:19+03:00');assert.equal(await page.locator('#iqamaCountdown').innerText(),'07:19');
  await time('2026-09-30T18:12:05+03:00');assert.equal(await page.locator('#iqamaCountdown').innerText(),'13:05');
  await time('2026-09-30T18:14:00+03:00');assert.equal(await page.locator('#iqamaStatus').isVisible(),false);assert.equal(await page.locator('#countdownSeparator').isVisible(),false);assert.equal(await page.locator('#nextPrayerCountdown').isVisible(),true);
  await page.waitForTimeout(1500);assert.equal(await page.locator('#iqamaStatus').isVisible(),false);
  assert.deepEqual(errors,[]);
  console.log('PASS: mobile drawer grouping/back navigation, independent saved durations, reload, live timing, expiry hides even with interface toggle on');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
